// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhotoGallery.Infrastructure.Persistence;

#nullable disable

namespace PhotoGallery.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GalleryDbContext))]
    [Migration("20260830022410_RenamePeersToKnownMachines")]
    partial class RenamePeersToKnownMachines
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.19");

            modelBuilder.Entity("PhotoGallery.Domain.Assets.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FacesDetectedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("IndexedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<long>("Length")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LocationReadUtc")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PerceptualHash")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("PhotoSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlaceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("QuarantinedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RotatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RotatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rotation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("TakenUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash");

                    b.HasIndex("FacesDetectedUtc");

                    b.HasIndex("Length");

                    b.HasIndex("LocationReadUtc");

                    b.HasIndex("PlaceId");

                    b.HasIndex("Status");

                    b.HasIndex("TakenUtc");

                    b.HasIndex("PhotoSourceId", "RelativePath")
                        .IsUnique();

                    b.ToTable("Assets", (string)null);
                });

            modelBuilder.Entity("PhotoGallery.Domain.Assets.VideoKeyframe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("Position")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssetId", "Ordinal")
                        .IsUnique();

                    b.ToTable("VideoKeyframes", (string)null);
                });

            modelBuilder.Entity("PhotoGallery.Domain.Collections.Collection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BuiltUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("CoverAssetId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NamedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Origin")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlaceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProposalKey")
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RuleFromUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RuleToUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CoverAssetId");

                    b.HasIndex("Origin");

                    b.HasIndex("PlaceId");

                    b.HasIndex("ProposalKey")
                        .IsUnique();

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("StartUtc");

                    b.ToTable("Collections", (string)null);
                });

            modelBuilder.Entity("PhotoGallery.Domain.Collections.CollectionMember", b =>
                {
                    b.Property<int>("AssetId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("AddedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("CollectionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AssetId");

                    b.HasIndex("CollectionId");

                    b.ToTable("CollectionMembers", (string)null);
                });

            modelBuilder.Entity("PhotoGallery.Domain.Collections.CollectionRejection", b =>
                {
                    b.Property<int>("AssetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProposalKey")
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RejectedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RejectedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("AssetId", "ProposalKey");

                    b.HasIndex("ProposalKey");

                    b.ToTable("CollectionRejections", (string)null);
                });

            modelBuilder.Entity("PhotoGallery.Domain.Collections.CollectionRulePerson", b =>
                {
                    b.Property<int>("CollectionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CollectionId", "PersonId");

                    b.HasIndex("PersonId");

                    b.ToTable("CollectionRulePeople", (string)null);
                });

            modelBuilder.Entity("PhotoGallery.Domain.Collections.CollectionRulePlace", b =>
                {
                    b.Property<int>("CollectionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlaceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CollectionId", "PlaceId");

                    b.HasIndex("PlaceId");

                    b.ToTable("CollectionRulePlaces", (string)null);
                });

            modelBuilder.Entity("PhotoGallery.Domain.Duplicates.DuplicateMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Distance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DuplicateSetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("DuplicateSetId", "AssetId")
                        .IsUnique();

                    b.ToTable("DuplicateMembers", (string)null);
                });

            modelBuilder.Entity("PhotoGallery.Domain.Duplicates.DuplicateSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DetectedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Kind", "IsResolved");

                    b.ToTable("DuplicateSets", (string)null);
                });

            modelBuilder.Entity("PhotoGallery.Domain.Faces.Face", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssetId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("DetectScore")
                        .HasColumnType("REAL");

                    b.Property<byte[]>("Embedding")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<Guid>("IgnoredBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("IgnoredUtc")
                        .HasColumnType("TEXT");

                    b.ComplexProperty<Dictionary<string, object>>("Bounds", "PhotoGallery.Domain.Faces.Face.Bounds#FaceBounds", b1 =>
                        {
                            b1.Property<int>("Height")
                                .HasColumnType("INTEGER")
                                .HasColumnName("BoundsHeight");

                            b1.Property<int>("Width")
                                .HasColumnType("INTEGER")
                                .HasColumnName("BoundsWidth");

                            b1.Property<int>("X")
                                .HasColumnType("INTEGER")
                                .HasColumnName("BoundsX");

                            b1.Property<int>("Y")
                                .HasColumnType("INTEGER")
                                .HasColumnName("BoundsY");
                        });

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.ToTable("Faces", (string)null);
                });

            modelBuilder.Entity("PhotoGallery.Domain.Library.LibrarySettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<double>("GalleryCellSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(200.0);

                    b.Property<int>("GallerySortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("LastScanUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MachineId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("NavigationCollapsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("SharedFolder")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("Theme")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("LibrarySettings", (string)null);
                });

            modelBuilder.Entity("PhotoGallery.Domain.Library.PhotoSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastScanUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SharedId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.HasIndex("SharedId")
                        .IsUnique();

                    b.ToTable("PhotoSources", (string)null);
                });

            modelBuilder.Entity("PhotoGallery.Domain.People.FaceAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DecidedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DecidedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("FaceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("Score")
                        .HasColumnType("REAL");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FaceId", "PersonId")
                        .IsUnique();

                    b.HasIndex("PersonId", "Source");

                    b.ToTable("FaceAssignments", (string)null);
                });

            modelBuilder.Entity("PhotoGallery.Domain.People.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BirthYear")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DisplayName")
                        .IsUnique()
                        .HasFilter("\"DeletedUtc\" IS NULL");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("People", (string)null);
                });

            modelBuilder.Entity("PhotoGallery.Domain.People.PersonEra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Centroid")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("FromUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SampleCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ToUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonId", "FromUtc");

                    b.ToTable("PersonEras", (string)null);
                });

            modelBuilder.Entity("PhotoGallery.Domain.Places.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Admin1Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryCode")
                        .HasColumnType("TEXT");

                    b.Property<int>("GeoNameId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GeoNameId")
                        .IsUnique();

                    b.ToTable("Places", (string)null);
                });

            modelBuilder.Entity("PhotoGallery.Domain.Search.PhotoContent", b =>
                {
                    b.Property<int>("AssetId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("IndexedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Vector")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("AssetId");

                    b.HasIndex("ThumbnailName");

                    b.ToTable("PhotoContent", (string)null);
                });

            modelBuilder.Entity("PhotoGallery.Domain.Sharing.HeldDecision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DecidedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FromMachine")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Part")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SharedSourceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SharedSourceId", "RelativePath");

                    b.HasIndex("SharedSourceId", "RelativePath", "Kind", "Part")
                        .IsUnique();

                    b.ToTable("HeldDecisions", (string)null);
                });

            modelBuilder.Entity("PhotoGallery.Domain.Sharing.KnownMachine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastMergedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MachineId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MachineId")
                        .IsUnique();

                    b.ToTable("KnownMachines", (string)null);
                });

            modelBuilder.Entity("PhotoGallery.Domain.Sharing.PairedSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DecidedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Left")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PairedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Right")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Left", "Right")
                        .IsUnique();

                    b.ToTable("PairedSources", (string)null);
                });

            modelBuilder.Entity("PhotoGallery.Domain.Assets.Asset", b =>
                {
                    b.HasOne("PhotoGallery.Domain.Library.PhotoSource", null)
                        .WithMany()
                        .HasForeignKey("PhotoSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PhotoGallery.Domain.Assets.VideoKeyframe", b =>
                {
                    b.HasOne("PhotoGallery.Domain.Assets.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("PhotoGallery.Domain.Collections.CollectionMember", b =>
                {
                    b.HasOne("PhotoGallery.Domain.Assets.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhotoGallery.Domain.Collections.Collection", "Collection")
                        .WithMany("Members")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("PhotoGallery.Domain.Collections.CollectionRejection", b =>
                {
                    b.HasOne("PhotoGallery.Domain.Assets.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("PhotoGallery.Domain.Collections.CollectionRulePerson", b =>
                {
                    b.HasOne("PhotoGallery.Domain.Collections.Collection", "Collection")
                        .WithMany("RulePeople")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhotoGallery.Domain.People.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("PhotoGallery.Domain.Collections.CollectionRulePlace", b =>
                {
                    b.HasOne("PhotoGallery.Domain.Collections.Collection", "Collection")
                        .WithMany("RulePlaces")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhotoGallery.Domain.Places.Place", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("Place");
                });

            modelBuilder.Entity("PhotoGallery.Domain.Duplicates.DuplicateMember", b =>
                {
                    b.HasOne("PhotoGallery.Domain.Assets.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhotoGallery.Domain.Duplicates.DuplicateSet", "DuplicateSet")
                        .WithMany("Members")
                        .HasForeignKey("DuplicateSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("DuplicateSet");
                });

            modelBuilder.Entity("PhotoGallery.Domain.Faces.Face", b =>
                {
                    b.HasOne("PhotoGallery.Domain.Assets.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("PhotoGallery.Domain.People.FaceAssignment", b =>
                {
                    b.HasOne("PhotoGallery.Domain.Faces.Face", "Face")
                        .WithMany()
                        .HasForeignKey("FaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhotoGallery.Domain.People.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Face");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("PhotoGallery.Domain.People.PersonEra", b =>
                {
                    b.HasOne("PhotoGallery.Domain.People.Person", "Person")
                        .WithMany("Eras")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("PhotoGallery.Domain.Search.PhotoContent", b =>
                {
                    b.HasOne("PhotoGallery.Domain.Assets.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("PhotoGallery.Domain.Collections.Collection", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("RulePeople");

                    b.Navigation("RulePlaces");
                });

            modelBuilder.Entity("PhotoGallery.Domain.Duplicates.DuplicateSet", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("PhotoGallery.Domain.People.Person", b =>
                {
                    b.Navigation("Eras");
                });
#pragma warning restore 612, 618
        }
    }
}
