// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhotoGallery.Infrastructure.Persistence;

#nullable disable

namespace PhotoGallery.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GalleryDbContext))]
    [Migration("20260814053121_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.19");

            modelBuilder.Entity("PhotoGallery.Domain.Assets.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Length")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PerceptualHash")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TakenUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash");

                    b.HasIndex("Length");

                    b.HasIndex("RelativePath")
                        .IsUnique();

                    b.HasIndex("TakenUtc");

                    b.ToTable("Assets", (string)null);
                });

            modelBuilder.Entity("PhotoGallery.Domain.Duplicates.DuplicateMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Distance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DuplicateSetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("DuplicateSetId", "AssetId")
                        .IsUnique();

                    b.ToTable("DuplicateMembers", (string)null);
                });

            modelBuilder.Entity("PhotoGallery.Domain.Duplicates.DuplicateSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DetectedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Kind", "IsResolved");

                    b.ToTable("DuplicateSets", (string)null);
                });

            modelBuilder.Entity("PhotoGallery.Domain.Faces.Face", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssetId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("DetectScore")
                        .HasColumnType("REAL");

                    b.Property<byte[]>("Embedding")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.ComplexProperty<Dictionary<string, object>>("Bounds", "PhotoGallery.Domain.Faces.Face.Bounds#FaceBounds", b1 =>
                        {
                            b1.Property<int>("Height")
                                .HasColumnType("INTEGER")
                                .HasColumnName("BoundsHeight");

                            b1.Property<int>("Width")
                                .HasColumnType("INTEGER")
                                .HasColumnName("BoundsWidth");

                            b1.Property<int>("X")
                                .HasColumnType("INTEGER")
                                .HasColumnName("BoundsX");

                            b1.Property<int>("Y")
                                .HasColumnType("INTEGER")
                                .HasColumnName("BoundsY");
                        });

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.ToTable("Faces", (string)null);
                });

            modelBuilder.Entity("PhotoGallery.Domain.Library.LibrarySettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastScanUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LibraryRoot")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LibrarySettings", (string)null);
                });

            modelBuilder.Entity("PhotoGallery.Domain.People.FaceAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FaceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("Score")
                        .HasColumnType("REAL");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FaceId", "PersonId")
                        .IsUnique();

                    b.HasIndex("PersonId", "Source");

                    b.ToTable("FaceAssignments", (string)null);
                });

            modelBuilder.Entity("PhotoGallery.Domain.People.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DisplayName")
                        .IsUnique();

                    b.ToTable("People", (string)null);
                });

            modelBuilder.Entity("PhotoGallery.Domain.People.PersonEra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Centroid")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("FromUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SampleCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ToUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonId", "FromUtc");

                    b.ToTable("PersonEras", (string)null);
                });

            modelBuilder.Entity("PhotoGallery.Domain.Duplicates.DuplicateMember", b =>
                {
                    b.HasOne("PhotoGallery.Domain.Assets.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhotoGallery.Domain.Duplicates.DuplicateSet", "DuplicateSet")
                        .WithMany("Members")
                        .HasForeignKey("DuplicateSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("DuplicateSet");
                });

            modelBuilder.Entity("PhotoGallery.Domain.Faces.Face", b =>
                {
                    b.HasOne("PhotoGallery.Domain.Assets.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("PhotoGallery.Domain.People.FaceAssignment", b =>
                {
                    b.HasOne("PhotoGallery.Domain.Faces.Face", "Face")
                        .WithMany()
                        .HasForeignKey("FaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhotoGallery.Domain.People.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Face");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("PhotoGallery.Domain.People.PersonEra", b =>
                {
                    b.HasOne("PhotoGallery.Domain.People.Person", "Person")
                        .WithMany("Eras")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("PhotoGallery.Domain.Duplicates.DuplicateSet", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("PhotoGallery.Domain.People.Person", b =>
                {
                    b.Navigation("Eras");
                });
#pragma warning restore 612, 618
        }
    }
}
