using System.Collections.Frozen;

namespace PhotoGallery.Infrastructure.Places;

/// <summary>
/// Turns the gazetteer's country codes into names a person would type.
/// </summary>
/// <remarks>
/// The gazetteer stores "HK", not "Hong Kong", and in a dense city the nearest
/// populated place is always a district - so without this a library of Hong Kong
/// photographs is filed under Tsim Sha Tsui, Central and Mid Levels, and the word
/// somebody would actually search for matches nothing at all.
///
/// <para>Written out here rather than shipped as a second data file. It is 246
/// lines of the most stable reference data there is, it needs no decompression
/// and no provenance note, and a table this size in source can be read and
/// corrected by anyone. The 246 are exactly the codes the embedded gazetteer
/// uses, and <c>CountryNamesTests</c> holds them to that: a code appearing in the
/// data with no name here fails the build's test run rather than quietly
/// labelling somebody's holiday with a two-letter code.</para>
///
/// <para>Short names, as a person says them - "Vietnam", not "Viet Nam"; "South
/// Korea", not "Korea, Republic of". This is what gets typed into a search box,
/// so it is spelled the way it gets typed.</para>
///
/// <para><c>XK</c> is Kosovo, which has no ISO code of its own; GeoNames uses the
/// user-assigned one and so does this.</para>
/// </remarks>
internal static class CountryNames
{
    /// <summary>The name for a code, or null when it is not one we know.</summary>
    public static string? Of(string? code) =>
        code is not null && s_names.TryGetValue(code, out string? name) ? name : null;

    /// <summary>Every code this knows, for the test that checks nothing is missing.</summary>
    public static IReadOnlyCollection<string> Codes => s_names.Keys;

    private static readonly FrozenDictionary<string, string> s_names =
        new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["AD"] = "Andorra",
            ["AE"] = "United Arab Emirates",
            ["AF"] = "Afghanistan",
            ["AG"] = "Antigua and Barbuda",
            ["AI"] = "Anguilla",
            ["AL"] = "Albania",
            ["AM"] = "Armenia",
            ["AO"] = "Angola",
            ["AR"] = "Argentina",
            ["AS"] = "American Samoa",
            ["AT"] = "Austria",
            ["AU"] = "Australia",
            ["AW"] = "Aruba",
            ["AX"] = "Åland Islands",
            ["AZ"] = "Azerbaijan",
            ["BA"] = "Bosnia and Herzegovina",
            ["BB"] = "Barbados",
            ["BD"] = "Bangladesh",
            ["BE"] = "Belgium",
            ["BF"] = "Burkina Faso",
            ["BG"] = "Bulgaria",
            ["BH"] = "Bahrain",
            ["BI"] = "Burundi",
            ["BJ"] = "Benin",
            ["BL"] = "Saint Barthélemy",
            ["BM"] = "Bermuda",
            ["BN"] = "Brunei",
            ["BO"] = "Bolivia",
            ["BQ"] = "Caribbean Netherlands",
            ["BR"] = "Brazil",
            ["BS"] = "Bahamas",
            ["BT"] = "Bhutan",
            ["BW"] = "Botswana",
            ["BY"] = "Belarus",
            ["BZ"] = "Belize",
            ["CA"] = "Canada",
            ["CC"] = "Cocos Islands",
            ["CD"] = "Democratic Republic of the Congo",
            ["CF"] = "Central African Republic",
            ["CG"] = "Republic of the Congo",
            ["CH"] = "Switzerland",
            ["CI"] = "Ivory Coast",
            ["CK"] = "Cook Islands",
            ["CL"] = "Chile",
            ["CM"] = "Cameroon",
            ["CN"] = "China",
            ["CO"] = "Colombia",
            ["CR"] = "Costa Rica",
            ["CU"] = "Cuba",
            ["CV"] = "Cape Verde",
            ["CW"] = "Curaçao",
            ["CX"] = "Christmas Island",
            ["CY"] = "Cyprus",
            ["CZ"] = "Czechia",
            ["DE"] = "Germany",
            ["DJ"] = "Djibouti",
            ["DK"] = "Denmark",
            ["DM"] = "Dominica",
            ["DO"] = "Dominican Republic",
            ["DZ"] = "Algeria",
            ["EC"] = "Ecuador",
            ["EE"] = "Estonia",
            ["EG"] = "Egypt",
            ["EH"] = "Western Sahara",
            ["ER"] = "Eritrea",
            ["ES"] = "Spain",
            ["ET"] = "Ethiopia",
            ["FI"] = "Finland",
            ["FJ"] = "Fiji",
            ["FK"] = "Falkland Islands",
            ["FM"] = "Micronesia",
            ["FO"] = "Faroe Islands",
            ["FR"] = "France",
            ["GA"] = "Gabon",
            ["GB"] = "United Kingdom",
            ["GD"] = "Grenada",
            ["GE"] = "Georgia",
            ["GF"] = "French Guiana",
            ["GG"] = "Guernsey",
            ["GH"] = "Ghana",
            ["GI"] = "Gibraltar",
            ["GL"] = "Greenland",
            ["GM"] = "Gambia",
            ["GN"] = "Guinea",
            ["GP"] = "Guadeloupe",
            ["GQ"] = "Equatorial Guinea",
            ["GR"] = "Greece",
            ["GS"] = "South Georgia and the South Sandwich Islands",
            ["GT"] = "Guatemala",
            ["GU"] = "Guam",
            ["GW"] = "Guinea-Bissau",
            ["GY"] = "Guyana",
            ["HK"] = "Hong Kong",
            ["HN"] = "Honduras",
            ["HR"] = "Croatia",
            ["HT"] = "Haiti",
            ["HU"] = "Hungary",
            ["ID"] = "Indonesia",
            ["IE"] = "Ireland",
            ["IL"] = "Israel",
            ["IM"] = "Isle of Man",
            ["IN"] = "India",
            ["IO"] = "British Indian Ocean Territory",
            ["IQ"] = "Iraq",
            ["IR"] = "Iran",
            ["IS"] = "Iceland",
            ["IT"] = "Italy",
            ["JE"] = "Jersey",
            ["JM"] = "Jamaica",
            ["JO"] = "Jordan",
            ["JP"] = "Japan",
            ["KE"] = "Kenya",
            ["KG"] = "Kyrgyzstan",
            ["KH"] = "Cambodia",
            ["KI"] = "Kiribati",
            ["KM"] = "Comoros",
            ["KN"] = "Saint Kitts and Nevis",
            ["KP"] = "North Korea",
            ["KR"] = "South Korea",
            ["KW"] = "Kuwait",
            ["KY"] = "Cayman Islands",
            ["KZ"] = "Kazakhstan",
            ["LA"] = "Laos",
            ["LB"] = "Lebanon",
            ["LC"] = "Saint Lucia",
            ["LI"] = "Liechtenstein",
            ["LK"] = "Sri Lanka",
            ["LR"] = "Liberia",
            ["LS"] = "Lesotho",
            ["LT"] = "Lithuania",
            ["LU"] = "Luxembourg",
            ["LV"] = "Latvia",
            ["LY"] = "Libya",
            ["MA"] = "Morocco",
            ["MC"] = "Monaco",
            ["MD"] = "Moldova",
            ["ME"] = "Montenegro",
            ["MF"] = "Saint Martin",
            ["MG"] = "Madagascar",
            ["MH"] = "Marshall Islands",
            ["MK"] = "North Macedonia",
            ["ML"] = "Mali",
            ["MM"] = "Myanmar",
            ["MN"] = "Mongolia",
            ["MO"] = "Macao",
            ["MP"] = "Northern Mariana Islands",
            ["MQ"] = "Martinique",
            ["MR"] = "Mauritania",
            ["MS"] = "Montserrat",
            ["MT"] = "Malta",
            ["MU"] = "Mauritius",
            ["MV"] = "Maldives",
            ["MW"] = "Malawi",
            ["MX"] = "Mexico",
            ["MY"] = "Malaysia",
            ["MZ"] = "Mozambique",
            ["NA"] = "Namibia",
            ["NC"] = "New Caledonia",
            ["NE"] = "Niger",
            ["NF"] = "Norfolk Island",
            ["NG"] = "Nigeria",
            ["NI"] = "Nicaragua",
            ["NL"] = "Netherlands",
            ["NO"] = "Norway",
            ["NP"] = "Nepal",
            ["NR"] = "Nauru",
            ["NU"] = "Niue",
            ["NZ"] = "New Zealand",
            ["OM"] = "Oman",
            ["PA"] = "Panama",
            ["PE"] = "Peru",
            ["PF"] = "French Polynesia",
            ["PG"] = "Papua New Guinea",
            ["PH"] = "Philippines",
            ["PK"] = "Pakistan",
            ["PL"] = "Poland",
            ["PM"] = "Saint Pierre and Miquelon",
            ["PN"] = "Pitcairn Islands",
            ["PR"] = "Puerto Rico",
            ["PS"] = "Palestine",
            ["PT"] = "Portugal",
            ["PW"] = "Palau",
            ["PY"] = "Paraguay",
            ["QA"] = "Qatar",
            ["RE"] = "Réunion",
            ["RO"] = "Romania",
            ["RS"] = "Serbia",
            ["RU"] = "Russia",
            ["RW"] = "Rwanda",
            ["SA"] = "Saudi Arabia",
            ["SB"] = "Solomon Islands",
            ["SC"] = "Seychelles",
            ["SD"] = "Sudan",
            ["SE"] = "Sweden",
            ["SG"] = "Singapore",
            ["SH"] = "Saint Helena",
            ["SI"] = "Slovenia",
            ["SJ"] = "Svalbard and Jan Mayen",
            ["SK"] = "Slovakia",
            ["SL"] = "Sierra Leone",
            ["SM"] = "San Marino",
            ["SN"] = "Senegal",
            ["SO"] = "Somalia",
            ["SR"] = "Suriname",
            ["SS"] = "South Sudan",
            ["ST"] = "São Tomé and Príncipe",
            ["SV"] = "El Salvador",
            ["SX"] = "Sint Maarten",
            ["SY"] = "Syria",
            ["SZ"] = "Eswatini",
            ["TC"] = "Turks and Caicos Islands",
            ["TD"] = "Chad",
            ["TF"] = "French Southern Territories",
            ["TG"] = "Togo",
            ["TH"] = "Thailand",
            ["TJ"] = "Tajikistan",
            ["TK"] = "Tokelau",
            ["TL"] = "Timor-Leste",
            ["TM"] = "Turkmenistan",
            ["TN"] = "Tunisia",
            ["TO"] = "Tonga",
            ["TR"] = "Turkey",
            ["TT"] = "Trinidad and Tobago",
            ["TV"] = "Tuvalu",
            ["TW"] = "Taiwan",
            ["TZ"] = "Tanzania",
            ["UA"] = "Ukraine",
            ["UG"] = "Uganda",
            ["US"] = "United States",
            ["UY"] = "Uruguay",
            ["UZ"] = "Uzbekistan",
            ["VA"] = "Vatican City",
            ["VC"] = "Saint Vincent and the Grenadines",
            ["VE"] = "Venezuela",
            ["VG"] = "British Virgin Islands",
            ["VI"] = "United States Virgin Islands",
            ["VN"] = "Vietnam",
            ["VU"] = "Vanuatu",
            ["WF"] = "Wallis and Futuna",
            ["WS"] = "Samoa",
            ["XK"] = "Kosovo",
            ["YE"] = "Yemen",
            ["YT"] = "Mayotte",
            ["ZA"] = "South Africa",
            ["ZM"] = "Zambia",
            ["ZW"] = "Zimbabwe",
        }.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase);
}
